### ISSUE TITLE
日志优化建议

### ISSUE THREAD

**Issue by LukyBruce** [besscroft/diyfile#36]
flyway 的mysql 依赖没有添加 也显示数据库初始完毕，但是后面一堆错误    

boolean noSupportDBFound = true;
            for (DatabaseType type : SORTED_DATABASE_TYPES) {
                if (type.handlesDatabaseProductNameAndVersion(databaseProductName, databaseProductVersion, dataSource.getConnection())) {
                    log.info("数据库版本支持自动初始化，即将开始初始化...");
                    Flyway flyway = Flyway.configure().dataSource(dataSource).outOfOrder(true).locations("db/" + dbType + "/migration").load();
                    flyway.migrate();
                    noSupportDBFound = false;
                    log.info("数据库初始化完毕！");
                    break;
                }
            }
            if(noSupportDBFound){
                throw new DiyFileException("Unable to find a Flyway plugin for database: " + databaseProductName + " with version: " + databaseProductVersion + " and type: " + dbType + ".");
            }

**Comment by besscroft** [comment]
感谢您的建议！方便的话可以提供一下复现场景吗？比如启动参数、指定的数据库版本、执行环境之类的，我这边好方便调试，谢谢~

**Comment by LukyBruce** [comment]
mac os m2.
dev profile
mysql docker latest
默认代码拉下来 没有 flyway-mysql 这个依赖。所以plugin for mysql 根本找不到 但是你的日志里面会显示初始化完毕。

**Comment by besscroft** [comment]
感谢您的反馈，我打开了一个 PR，也许能满足您的需求~
